### ISSUE TITLE
is possible to validate dates contains time

### ISSUE THREAD

**Issue by ahmadbadpey** [halaei/jalali#2]
suppose we have a date-time jalali date format like this : 
`"21/02/1395 21:30"
`
is your solution can validate it Correctly?or do you have any ideas for that?

**Comment by halaei** [comment]
This package does not provide facilities for validating hour, min, and seconds for now. Any pull request to fix it will be appreciated.
One solution for that, is to separate date part from time part into 2 inputs, if you have that flexibility.
Then validate jalali date with this packages (jalali:d/m/Y) and the time part with the rules provided by the laravel/framework itself.
The reason I did not care for time in this package as well as [opilo/farsi](https://github.com/opilo/farsi/) was that Iranian time (e.g. 21:30:00) is not different from Georgian one.

**Comment by ahmadbadpey** [comment]
Unfortunately , all my dates format is based on **DateTime** (`YYYY-MM-DD HH:MM:SS`) in jalali that is a common date format in php and Laravel applications. I hope you add this capability to your validation package.

**Comment by halaei** [comment]
Ok. I will try to do it in a week.

**Comment by halaei** [comment]
@ahmadbadpey please check the [opilo/farsi](https://github.com/opilo/farsi) package. I moved codes from this package there and added JDateTime class, together with `jdatetime`, `jdatetime_before`, and `jdatetime_after` rules.

``` php
    $v = Validator::make([
            'start_time' => '1395/02/16 12:10:00',
        ],
        [
            'start_time' => 'required|jdatetime_after:"1395/01/01 00:00:00"|jdatetime_before:"1396/01/01 00:00:00"',
        ]);
```

After the next release of [opilo/farsi](https://github.com/opilo/farsi), `halaei/jalali` package (this repository) will be discontinued.

**Comment by ahmadbadpey** [comment]
Thank you very much @halaei,
I was waiting for you changes.
